### ISSUE TITLE
Towering issues

### ISSUE THREAD

**Issue by iiAnthony** [avolkov1/keras_experiments#3]
Hi,

I'm trying to make GPU parallel exec of a model wit the help of your "multigpu" approach.
Here is the piece of code where I inserted the make_parallel part.
   
```
       model_rpn = Model(img_input, rpn_layers)
       model_classifier = Model([feature_map_input, roi_input], classifier)

       model_rpn.load_weights(C.model_path, by_name=True)
       model_classifier.load_weights(C.model_path, by_name=True)

        # Use multi GPU support       
        gpus = get_available_gpus()
        model_rpn = make_parallel(model_rpn, gpus)
        model_classifier = make_parallel(model_classifier, gpus)

        model_rpn.compile(optimizer='sgd', loss='mse')
        model_classifier.compile(optimizer='sgd', loss='mse')
```

I am facing a strange issue not reported here :
```
Traceback (most recent call last):
  File "ex.py", line 40, in <module>
    model_rpn, model_classifier = initModel(config)
  File "testing.py", line 183, in initModel
    rpn = make_parallel(model_rpn, gpus)
  File "multigpu.py", line 470, in make_parallel
    enqueue=enqueue, usenccl=usenccl,initsync=initsync, syncopt=syncopt)
  File "multigpu.py", line 224, in __init__
    **kwargs)
  File "multigpu.py", line 325, in _init_make_dataparallel
    params = modeltower.graph._collections['trainable_variables']
  AttributeError: 'list' object has no attribute 'graph'
```

As you see , the "modeltower' is a list as it is computed from `modeltower = model_(slices)` where 'model_' is a keras model. It thus seems normal that modeltower is a list.

In your multigpu file, there is some commented lines for retrieving the params. I chose to comment the graph line to retrieve weights from lines above `params = model_.trainable_weights`. This allows to go through but the code fails some lines after when asserting that everything goes well at `merged = Concatenate(axis=0)(towers)`    with the error  

```
  Traceback (most recent call last):
  File "ex.py", line 40, in <module>
    model_rpn, model_classifier = initModel(config)

  File "testing.py", line 183, in initModel
    rpn = make_parallel(model_rpn, gpus)
  File "multigpu.py", line 469, in make_parallel
    enqueue=enqueue, usenccl=usenccl,initsync=initsync, syncopt=syncopt)
  File "multigpu.py", line 224, in __init__
    **kwargs)
  File "multigpu.py", line 330, in _init_make_dataparallel
    merged = Concatenate(axis=0)(towers)
  File "topology.py", line 552, in __call__
    self.assert_input_compatibility(inputs)
  File "topology.py", line 425, in assert_input_compatibility
    str(inputs) + '. All inputs to the layer '
ValueError: Layer concatenate_1 was called with an input that isn't a symbolic tensor. Received type: <type 'list'>. Full input: [[<tf.Tensor 'tower_0/model_1/rpn_out_class/Sigmoid:0' shape=(?, ?, ?, 9) dtype=float32>, <tf.Tensor 'tower_0/model_1/rpn_out_regress/BiasAdd:0' shape=(?, ?, ?, 36) dtype=float32>, <tf.Tensor 'tower_0/model_1/activation_40/Relu:0' shape=(?, ?, ?, 1024) dtype=float32>], [<tf.Tensor 'tower_1/model_1/rpn_out_class/Sigmoid:0' shape=(?, ?, ?, 9) dtype=float32>, <tf.Tensor 'tower_1/model_1/rpn_out_regress/BiasAdd:0' shape=(?, ?, ?, 36) dtype=float32>, <tf.Tensor 'tower_1/model_1/activation_40/Relu:0' shape=(?, ?, ?, 1024) dtype=float32>]]. All inputs to the layer should be tensors.

```
Did I miss something in the use of the multigpu ?
I am looking for the issue on my side , but maybe someone already had similar pb and could provide help in finding my miss.

Thanks a lot for your work.
Regards

Notice:  I do not use optimizers, I kept original keras optim (Adam one); I have two GPUs (Quadro P6000, major: 6 minor: 1 memoryClockRate (GHz) 1.645) .

**Comment by avolkov1** [comment]
@iiAnthony  I'll take a look at it. Can you provide more details on this part:

```
model_rpn = Model(img_input, rpn_layers)
model_classifier = Model([feature_map_input, roi_input], classifier)
```
Does non-multigpu work fine? Some code or example of what img_input is, what rpn_layers are, etc.

**Comment by iiAnthony** [comment]
Hi, thanks for your answer.

Yes everything works well without the "multigpu" part. Tensorflow makes use of one GPU to proceed. But I have two cards, well identified at start:
```
pciBusID 0000:04:00.0 
Total memory: 23.87GiB
Free memory: 1.03GiB
2017-08-11 09:10:34.773574: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 1
2017-08-11 09:10:34.773587: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y Y 
2017-08-11 09:10:34.773593: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 1:   Y Y
2017-08-11 09:10:34.773605: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating 
TensorFlow device (/gpu:0) -> (device: 0, name: Quadro P6000, pci bus id: 0000:03:00.0)
2017-08-11 09:10:34.773612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating 
TensorFlow device (/gpu:1) -> (device: 1, name: Quadro P6000, pci bus id: 0000:04:00.0)
```


'Model' is a `from keras.models import Model`  object.
`img_input = Input(shape=input_shape_img)`
`feature_map_input = Input(shape=input_shape_features)`
rpn_layers and classifier are build from the resnet50 model with specific parts. The base code is from the keras impl of the "Faster R CNN" at : github.com/yhenon/keras-frcnn

Specifically `rpn_layers = keras_frcnn.resnet.rpn(shared_layers, num_anchors)` and `classifier = keras_frcnn.resnet.classifier(feature_map_input, roi_input, C.num_rois, nb_classes=len(C.class_mapping))`  which both return a keras Model.


Here is a summary of the RPN model (`model_rpn.summary()`): 

```
Layer (type)                     Output Shape          Param #     Connected to         
            
====================================================================================================
input_1 (InputLayer)             (None, None, None, 3) 0                                            
____________________________________________________________________________________________________
zero_padding2d_1 (ZeroPadding2D) (None, None, None, 3) 0           input_1[0][0]                    
____________________________________________________________________________________________________
conv1 (Conv2D)                   (None, None, None, 64 9472        zero_padding2d_1[0][0]           
____________________________________________________________________________________________________
bn_conv1 (FixedBatchNormalizatio (None, None, None, 64 256         conv1[0][0]                      
____________________________________________________________________________________________________
activation_1 (Activation)        (None, None, None, 64 0           bn_conv1[0][0]                   
____________________________________________________________________________________________________
max_pooling2d_1 (MaxPooling2D)   (None, None, None, 64 0           activation_1[0][0]               
____________________________________________________________________________________________________
res2a_branch2a (Conv2D)          (None, None, None, 64 4160        max_pooling2d_1[0][0]            
____________________________________________________________________________________________________
bn2a_branch2a (FixedBatchNormali (None, None, None, 64 256         res2a_branch2a[0][0]             
____________________________________________________________________________________________________
activation_2 (Activation)        (None, None, None, 64 0           bn2a_branch2a[0][0]              
____________________________________________________________________________________________________
res2a_branch2b (Conv2D)          (None, None, None, 64 36928       activation_2[0][0]               
____________________________________________________________________________________________________
bn2a_branch2b (FixedBatchNormali (None, None, None, 64 256         res2a_branch2b[0][0]             
____________________________________________________________________________________________________
activation_3 (Activation)        (None, None, None, 64 0           bn2a_branch2b[0][0]              
____________________________________________________________________________________________________
res2a_branch2c (Conv2D)          (None, None, None, 25 16640       activation_3[0][0]               
____________________________________________________________________________________________________
res2a_branch1 (Conv2D)           (None, None, None, 25 16640       max_pooling2d_1[0][0]            
____________________________________________________________________________________________________
bn2a_branch2c (FixedBatchNormali (None, None, None, 25 1024        res2a_branch2c[0][0]             
____________________________________________________________________________________________________
bn2a_branch1 (FixedBatchNormaliz (None, None, None, 25 1024        res2a_branch1[0][0]              
____________________________________________________________________________________________________
add_1 (Add)                      (None, None, None, 25 0           bn2a_branch2c[0][0]              
                                                                   bn2a_branch1[0][0]               
____________________________________________________________________________________________________
activation_4 (Activation)        (None, None, None, 25 0           add_1[0][0]                      
____________________________________________________________________________________________________
res2b_branch2a (Conv2D)          (None, None, None, 64 16448       activation_4[0][0]               
____________________________________________________________________________________________________
bn2b_branch2a (FixedBatchNormali (None, None, None, 64 256         res2b_branch2a[0][0]             
____________________________________________________________________________________________________
activation_5 (Activation)        (None, None, None, 64 0           bn2b_branch2a[0][0]              
____________________________________________________________________________________________________
res2b_branch2b (Conv2D)          (None, None, None, 64 36928       activation_5[0][0]               
____________________________________________________________________________________________________
bn2b_branch2b (FixedBatchNormali (None, None, None, 64 256         res2b_branch2b[0][0]             
____________________________________________________________________________________________________
activation_6 (Activation)        (None, None, None, 64 0           bn2b_branch2b[0][0]              
____________________________________________________________________________________________________
res2b_branch2c (Conv2D)          (None, None, None, 25 16640       activation_6[0][0]               
____________________________________________________________________________________________________
bn2b_branch2c (FixedBatchNormali (None, None, None, 25 1024        res2b_branch2c[0][0]             
____________________________________________________________________________________________________
add_2 (Add)                      (None, None, None, 25 0           bn2b_branch2c[0][0]              
                                                                   activation_4[0][0]               
____________________________________________________________________________________________________
activation_7 (Activation)        (None, None, None, 25 0           add_2[0][0]                      
____________________________________________________________________________________________________
res2c_branch2a (Conv2D)          (None, None, None, 64 16448       activation_7[0][0]               
____________________________________________________________________________________________________
bn2c_branch2a (FixedBatchNormali (None, None, None, 64 256         res2c_branch2a[0][0]             
____________________________________________________________________________________________________
activation_8 (Activation)        (None, None, None, 64 0           bn2c_branch2a[0][0]              
____________________________________________________________________________________________________
res2c_branch2b (Conv2D)          (None, None, None, 64 36928       activation_8[0][0]               
____________________________________________________________________________________________________
bn2c_branch2b (FixedBatchNormali (None, None, None, 64 256         res2c_branch2b[0][0]             
____________________________________________________________________________________________________
activation_9 (Activation)        (None, None, None, 64 0           bn2c_branch2b[0][0]              
____________________________________________________________________________________________________
res2c_branch2c (Conv2D)          (None, None, None, 25 16640       activation_9[0][0]               
____________________________________________________________________________________________________
bn2c_branch2c (FixedBatchNormali (None, None, None, 25 1024        res2c_branch2c[0][0]             
____________________________________________________________________________________________________
add_3 (Add)                      (None, None, None, 25 0           bn2c_branch2c[0][0]              
                                                                   activation_7[0][0]               
____________________________________________________________________________________________________
activation_10 (Activation)       (None, None, None, 25 0           add_3[0][0]                      
____________________________________________________________________________________________________
res3a_branch2a (Conv2D)          (None, None, None, 12 32896       activation_10[0][0]              
____________________________________________________________________________________________________
bn3a_branch2a (FixedBatchNormali (None, None, None, 12 512         res3a_branch2a[0][0]             
____________________________________________________________________________________________________
activation_11 (Activation)       (None, None, None, 12 0           bn3a_branch2a[0][0]              
____________________________________________________________________________________________________
res3a_branch2b (Conv2D)          (None, None, None, 12 147584      activation_11[0][0]              
____________________________________________________________________________________________________
bn3a_branch2b (FixedBatchNormali (None, None, None, 12 512         res3a_branch2b[0][0]             
____________________________________________________________________________________________________
activation_12 (Activation)       (None, None, None, 12 0           bn3a_branch2b[0][0]              
____________________________________________________________________________________________________
res3a_branch2c (Conv2D)          (None, None, None, 51 66048       activation_12[0][0]              
____________________________________________________________________________________________________
res3a_branch1 (Conv2D)           (None, None, None, 51 131584      activation_10[0][0]              
____________________________________________________________________________________________________
bn3a_branch2c (FixedBatchNormali (None, None, None, 51 2048        res3a_branch2c[0][0]             
____________________________________________________________________________________________________
bn3a_branch1 (FixedBatchNormaliz (None, None, None, 51 2048        res3a_branch1[0][0]              
____________________________________________________________________________________________________
add_4 (Add)                      (None, None, None, 51 0           bn3a_branch2c[0][0]              
                                                                   bn3a_branch1[0][0]               
____________________________________________________________________________________________________
activation_13 (Activation)       (None, None, None, 51 0           add_4[0][0]                      
____________________________________________________________________________________________________
res3b_branch2a (Conv2D)          (None, None, None, 12 65664       activation_13[0][0]              
____________________________________________________________________________________________________
bn3b_branch2a (FixedBatchNormali (None, None, None, 12 512         res3b_branch2a[0][0]             
____________________________________________________________________________________________________
activation_14 (Activation)       (None, None, None, 12 0           bn3b_branch2a[0][0]              
____________________________________________________________________________________________________
res3b_branch2b (Conv2D)          (None, None, None, 12 147584      activation_14[0][0]              
____________________________________________________________________________________________________
bn3b_branch2b (FixedBatchNormali (None, None, None, 12 512         res3b_branch2b[0][0]             
____________________________________________________________________________________________________
activation_15 (Activation)       (None, None, None, 12 0           bn3b_branch2b[0][0]              
____________________________________________________________________________________________________
res3b_branch2c (Conv2D)          (None, None, None, 51 66048       activation_15[0][0]              
____________________________________________________________________________________________________
bn3b_branch2c (FixedBatchNormali (None, None, None, 51 2048        res3b_branch2c[0][0]             
____________________________________________________________________________________________________
add_5 (Add)                      (None, None, None, 51 0           bn3b_branch2c[0][0]              
                                                                   activation_13[0][0]              
____________________________________________________________________________________________________
activation_16 (Activation)       (None, None, None, 51 0           add_5[0][0]                      
____________________________________________________________________________________________________
res3c_branch2a (Conv2D)          (None, None, None, 12 65664       activation_16[0][0]              
____________________________________________________________________________________________________
bn3c_branch2a (FixedBatchNormali (None, None, None, 12 512         res3c_branch2a[0][0]             
____________________________________________________________________________________________________
activation_17 (Activation)       (None, None, None, 12 0           bn3c_branch2a[0][0]              
____________________________________________________________________________________________________
res3c_branch2b (Conv2D)          (None, None, None, 12 147584      activation_17[0][0]              
____________________________________________________________________________________________________
bn3c_branch2b (FixedBatchNormali (None, None, None, 12 512         res3c_branch2b[0][0]             
____________________________________________________________________________________________________
activation_18 (Activation)       (None, None, None, 12 0           bn3c_branch2b[0][0]              
____________________________________________________________________________________________________
res3c_branch2c (Conv2D)          (None, None, None, 51 66048       activation_18[0][0]              
____________________________________________________________________________________________________
bn3c_branch2c (FixedBatchNormali (None, None, None, 51 2048        res3c_branch2c[0][0]             
____________________________________________________________________________________________________
add_6 (Add)                      (None, None, None, 51 0           bn3c_branch2c[0][0]              
                                                                   activation_16[0][0]              
____________________________________________________________________________________________________
activation_19 (Activation)       (None, None, None, 51 0           add_6[0][0]                      
____________________________________________________________________________________________________
res3d_branch2a (Conv2D)          (None, None, None, 12 65664       activation_19[0][0]              
____________________________________________________________________________________________________
bn3d_branch2a (FixedBatchNormali (None, None, None, 12 512         res3d_branch2a[0][0]             
____________________________________________________________________________________________________
activation_20 (Activation)       (None, None, None, 12 0           bn3d_branch2a[0][0]              
____________________________________________________________________________________________________
res3d_branch2b (Conv2D)          (None, None, None, 12 147584      activation_20[0][0]              
____________________________________________________________________________________________________
bn3d_branch2b (FixedBatchNormali (None, None, None, 12 512         res3d_branch2b[0][0]             
____________________________________________________________________________________________________
activation_21 (Activation)       (None, None, None, 12 0           bn3d_branch2b[0][0]              
____________________________________________________________________________________________________
res3d_branch2c (Conv2D)          (None, None, None, 51 66048       activation_21[0][0]              
____________________________________________________________________________________________________
bn3d_branch2c (FixedBatchNormali (None, None, None, 51 2048        res3d_branch2c[0][0]             
____________________________________________________________________________________________________
add_7 (Add)                      (None, None, None, 51 0           bn3d_branch2c[0][0]              
                                                                   activation_19[0][0]              
____________________________________________________________________________________________________
activation_22 (Activation)       (None, None, None, 51 0           add_7[0][0]                      
____________________________________________________________________________________________________
res4a_branch2a (Conv2D)          (None, None, None, 25 131328      activation_22[0][0]              
____________________________________________________________________________________________________
bn4a_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4a_branch2a[0][0]             
____________________________________________________________________________________________________
activation_23 (Activation)       (None, None, None, 25 0           bn4a_branch2a[0][0]              
____________________________________________________________________________________________________
res4a_branch2b (Conv2D)          (None, None, None, 25 590080      activation_23[0][0]              
____________________________________________________________________________________________________
bn4a_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4a_branch2b[0][0]             
____________________________________________________________________________________________________
activation_24 (Activation)       (None, None, None, 25 0           bn4a_branch2b[0][0]              
____________________________________________________________________________________________________
res4a_branch2c (Conv2D)          (None, None, None, 10 263168      activation_24[0][0]              
____________________________________________________________________________________________________
res4a_branch1 (Conv2D)           (None, None, None, 10 525312      activation_22[0][0]              
____________________________________________________________________________________________________
bn4a_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4a_branch2c[0][0]             
____________________________________________________________________________________________________
bn4a_branch1 (FixedBatchNormaliz (None, None, None, 10 4096        res4a_branch1[0][0]              
____________________________________________________________________________________________________
add_8 (Add)                      (None, None, None, 10 0           bn4a_branch2c[0][0]              
                                                                   bn4a_branch1[0][0]               
____________________________________________________________________________________________________
activation_25 (Activation)       (None, None, None, 10 0           add_8[0][0]                      
____________________________________________________________________________________________________
res4b_branch2a (Conv2D)          (None, None, None, 25 262400      activation_25[0][0]              
____________________________________________________________________________________________________
bn4b_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4b_branch2a[0][0]             
____________________________________________________________________________________________________
activation_26 (Activation)       (None, None, None, 25 0           bn4b_branch2a[0][0]              
____________________________________________________________________________________________________
res4b_branch2b (Conv2D)          (None, None, None, 25 590080      activation_26[0][0]              
____________________________________________________________________________________________________
bn4b_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4b_branch2b[0][0]             
____________________________________________________________________________________________________
activation_27 (Activation)       (None, None, None, 25 0           bn4b_branch2b[0][0]              
____________________________________________________________________________________________________
res4b_branch2c (Conv2D)          (None, None, None, 10 263168      activation_27[0][0]              
____________________________________________________________________________________________________
bn4b_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4b_branch2c[0][0]             
____________________________________________________________________________________________________
add_9 (Add)                      (None, None, None, 10 0           bn4b_branch2c[0][0]              
                                                                   activation_25[0][0]              
____________________________________________________________________________________________________
activation_28 (Activation)       (None, None, None, 10 0           add_9[0][0]                      
____________________________________________________________________________________________________
res4c_branch2a (Conv2D)          (None, None, None, 25 262400      activation_28[0][0]              
____________________________________________________________________________________________________
bn4c_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4c_branch2a[0][0]             
____________________________________________________________________________________________________
activation_29 (Activation)       (None, None, None, 25 0           bn4c_branch2a[0][0]              
____________________________________________________________________________________________________
res4c_branch2b (Conv2D)          (None, None, None, 25 590080      activation_29[0][0]              
____________________________________________________________________________________________________
bn4c_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4c_branch2b[0][0]             
____________________________________________________________________________________________________
activation_30 (Activation)       (None, None, None, 25 0           bn4c_branch2b[0][0]              
____________________________________________________________________________________________________
res4c_branch2c (Conv2D)          (None, None, None, 10 263168      activation_30[0][0]              
____________________________________________________________________________________________________
bn4c_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4c_branch2c[0][0]             
____________________________________________________________________________________________________
add_10 (Add)                     (None, None, None, 10 0           bn4c_branch2c[0][0]              
                                                                   activation_28[0][0]              
____________________________________________________________________________________________________
activation_31 (Activation)       (None, None, None, 10 0           add_10[0][0]                     
____________________________________________________________________________________________________
res4d_branch2a (Conv2D)          (None, None, None, 25 262400      activation_31[0][0]              
____________________________________________________________________________________________________
bn4d_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4d_branch2a[0][0]             
____________________________________________________________________________________________________
activation_32 (Activation)       (None, None, None, 25 0           bn4d_branch2a[0][0]              
____________________________________________________________________________________________________
res4d_branch2b (Conv2D)          (None, None, None, 25 590080      activation_32[0][0]              
____________________________________________________________________________________________________
bn4d_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4d_branch2b[0][0]             
____________________________________________________________________________________________________
activation_33 (Activation)       (None, None, None, 25 0           bn4d_branch2b[0][0]              
____________________________________________________________________________________________________
res4d_branch2c (Conv2D)          (None, None, None, 10 263168      activation_33[0][0]              
____________________________________________________________________________________________________
bn4d_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4d_branch2c[0][0]             
____________________________________________________________________________________________________
add_11 (Add)                     (None, None, None, 10 0           bn4d_branch2c[0][0]              
                                                                   activation_31[0][0]              
____________________________________________________________________________________________________
activation_34 (Activation)       (None, None, None, 10 0           add_11[0][0]                     
____________________________________________________________________________________________________
res4e_branch2a (Conv2D)          (None, None, None, 25 262400      activation_34[0][0]              
____________________________________________________________________________________________________
bn4e_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4e_branch2a[0][0]             
____________________________________________________________________________________________________
activation_35 (Activation)       (None, None, None, 25 0           bn4e_branch2a[0][0]              
____________________________________________________________________________________________________
res4e_branch2b (Conv2D)          (None, None, None, 25 590080      activation_35[0][0]              
____________________________________________________________________________________________________
bn4e_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4e_branch2b[0][0]             
____________________________________________________________________________________________________
activation_36 (Activation)       (None, None, None, 25 0           bn4e_branch2b[0][0]              
____________________________________________________________________________________________________
res4e_branch2c (Conv2D)          (None, None, None, 10 263168      activation_36[0][0]              
____________________________________________________________________________________________________
bn4e_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4e_branch2c[0][0]             
____________________________________________________________________________________________________
add_12 (Add)                     (None, None, None, 10 0           bn4e_branch2c[0][0]              
                                                                   activation_34[0][0]              
____________________________________________________________________________________________________
activation_37 (Activation)       (None, None, None, 10 0           add_12[0][0]                     
____________________________________________________________________________________________________
res4f_branch2a (Conv2D)          (None, None, None, 25 262400      activation_37[0][0]              
____________________________________________________________________________________________________
bn4f_branch2a (FixedBatchNormali (None, None, None, 25 1024        res4f_branch2a[0][0]             
____________________________________________________________________________________________________
activation_38 (Activation)       (None, None, None, 25 0           bn4f_branch2a[0][0]              
____________________________________________________________________________________________________
res4f_branch2b (Conv2D)          (None, None, None, 25 590080      activation_38[0][0]              
____________________________________________________________________________________________________
bn4f_branch2b (FixedBatchNormali (None, None, None, 25 1024        res4f_branch2b[0][0]             
____________________________________________________________________________________________________
activation_39 (Activation)       (None, None, None, 25 0           bn4f_branch2b[0][0]              
____________________________________________________________________________________________________
res4f_branch2c (Conv2D)          (None, None, None, 10 263168      activation_39[0][0]              
____________________________________________________________________________________________________
bn4f_branch2c (FixedBatchNormali (None, None, None, 10 4096        res4f_branch2c[0][0]             
____________________________________________________________________________________________________
add_13 (Add)                     (None, None, None, 10 0           bn4f_branch2c[0][0]              
                                                                   activation_37[0][0]              
____________________________________________________________________________________________________
activation_40 (Activation)       (None, None, None, 10 0           add_13[0][0]                     
____________________________________________________________________________________________________
rpn_conv1 (Conv2D)               (None, None, None, 51 4719104     activation_40[0][0]              
____________________________________________________________________________________________________
rpn_out_class (Conv2D)           (None, None, None, 9) 4617        rpn_conv1[0][0]                  
____________________________________________________________________________________________________
rpn_out_regress (Conv2D)         (None, None, None, 36 18468       rpn_conv1[0][0]    
              
====================================================================================================
Total params: 13,331,373
Trainable params: 13,270,189
Non-trainable params: 61,184

```

I really don't get why the multigpu call does not work as every variable seems to be ok and you provide working examples.

Hope this helps, 
Thanks a lot.

Regards

**Comment by avolkov1** [comment]
@iiAnthony I see. I'm not handling the multi output case correctly. I'll fix it.

**Comment by iiAnthony** [comment]
@avolkov1 Great news that you found the issue ! :)  I'll keep in touch.
Thanks a lot.

**Comment by avolkov1** [comment]
@iiAnthony I fixed the multi-output issue. Refer to changes in ```keras_exp/multigpu/_multigpu.py``` done in commit [569a443](https://github.com/avolkov1/keras_experiments/commit/569a443894ca09fcf4beab24ba23dcb621515e08)

Also, refer to example:
[https://github.com/avolkov1/keras_experiments/blob/master/examples/faster_rcnn/train_frcnn_mgpu.py](https://github.com/avolkov1/keras_experiments/blob/master/examples/faster_rcnn/train_frcnn_mgpu.py)

But that example has issues not related to the towering issue you raised which I'm not going to fix. That stems from original implementation of:
[https://github.com/yhenon/keras-frcnn/blob/master/train_frcnn.py](https://github.com/yhenon/keras-frcnn/blob/master/train_frcnn.py)

I made the example work briefly. The original implementation train loop does 1 sample at a time. The multigpu implementation I'm using is data-parallelism. That requires that a mini-batch size matches at least the number of GPUs. This logic doesn't work for data-parallelism:
```
# from train_frcnn.py
X, Y, img_data = next(data_gen_train)
loss_rpn = model_rpn.train_on_batch(X, Y)
```
When:
```
X SHAPE: (1, 600, 800, 3)
Y 0 SHAPE: (1, 38, 50, 18)
Y 1 SHAPE: (1, 38, 50, 72)
```

I made it work by batching up a few examples. But the images vary in size. So do this effectively the images need to be sized/resized to the same reference size, and corresponding rois need to be adjusted. I just did the code below to demonstrate that it works.
```
# from train_frcnn_mgpu.py
dgroups = {}
nbatch_lim = 4 * ngpus
while True:
    X, Y, img_data = next(data_gen_train)

    if X.shape in dgroups:
        cat_flag = True
    else:
        cat_flag = False

    ref = dgroups.setdefault(X.shape, {'x': X, 'y': Y, 'cnt': 1})

    print('X SHAPE: {}'.format(ref['x'].shape))

    for jj in range(noutputs):
        print('Y {} SHAPE: {}'.format(jj, ref['y'][jj].shape))

    print('IMG_DATA: {}'.format(img_data))

    if cat_flag:
        ref['x'] = np.concatenate([ref['x'], X])
        ref['y'] = [np.concatenate(yy) for yy in zip(ref['y'], Y)]
        ref['cnt'] = ref['cnt'] + 1
        if ref['cnt'] == nbatch_lim:
            data_to_run = ref
            break

X, Y = data_to_run['x'], data_to_run['y']
print('\n\n')
print('BATCHED X SHAPE: {}'.format(X.shape))

for ii in range(noutputs):
    print('BATCHED Y {} SHAPE: {}'.format(ii, Y[ii].shape))

print('TRAINING, WATCH THE GPU UTILIZATION SPIKE ON ALL GPUS')
loss_rpn = model_rpn.train_on_batch(X, Y)

P_rpn = model_rpn.predict_on_batch(X)
print('\n\n ==================== WILL CRASH SOON. YOU FIX IT '
         '=======================\n\n')
```
With 4 GPUs (above ```nbatch_lim = 4 * ngpus```) That effectively does this:
```
X SHAPE: (16, 600, 800, 3)
Y 0 SHAPE: (16, 38, 50, 18)
Y 1 SHAPE: (16, 38, 50, 72)
```
Use the [gpustat](https://pypi.python.org/pypi/gpustat/0.3.1) utility to see that all your GPUs will spike in utilization when running ```model_rpn.train_on_batch```.

**Comment by tglauch** [comment]
Hi,

for me it seems that the problem still exists...using the keras Model for functional APIs I still get this error

      File "/scratch9/NN_Reco/Neural_Network.py", line 238, in <module>
    model = make_parallel(model_serial, gdev_list)
      File "/scratch9/NN_Reco/keras_exp/multigpu/_multigpu.py", line 496, in make_parallel
    initsync=initsync, syncopt=syncopt)
      File "/scratch9/NN_Reco/keras_exp/multigpu/_multigpu.py", line 236, in __init__
    **kwargs)
      File "/scratch9/NN_Reco/keras_exp/multigpu/_multigpu.py", line 335, in _init_make_dataparallel
    params = modeltower.graph._collections['trainable_variables']
    AttributeError: 'list' object has no attribute 'graph'

I can provide more information if necessary. But the problem seems to be same as TOs...

**Comment by avolkov1** [comment]
@tglauch Looks like you're using outdated code. I updated the code. Refer to changes in keras_exp/multigpu/_multigpu.py done in commit 569a443

The code now is
```python

                # Handle multi-output case
                modeltower = model(slices)
                if not isinstance(modeltower, list):
                    modeltower = [modeltower]

                for imt, mt in enumerate(modeltower):
                    towers[imt].append(mt)
                    params = mt.graph._collections['trainable_variables']
```

So you should not be getting an error traceback like the one you cited unless you're using outdated code. This traceback is not possible with updated code.
```
params = modeltower.graph._collections['trainable_variables']
AttributeError: 'list' object has no attribute 'graph'
```
